---
name: ((deployment-name))

releases:
- name: rabbitmq-on-demand-release
  version: "1.0"

- name: routing
  version: latest

- name: bpm
  version: latest

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: ((stemcell-version))

instance_groups:
- name: rmq
  instances: 1
  jobs:
  - name: rabbitmq-server
    release: rabbitmq-on-demand-release
  vm_type: ((vm_type))
  stemcell: xenial
  persistent_disk_type: ((persistent_disk_type))
  networks:
  - name: default
  azs:
  - z6
update:
  canaries: 1
  canary_watch_time: 30000-180000
  update_watch_time: 30000-180000
  max_in_flight: 1
  serial: false

######### COMMON PROPERTIES ##########
properties:
  password: cheolhan1234
  port: 1444
  dashboard_port: 2224
  admin: ohoh
#  port: "((service_port))"
