# Spring properties
spring:
  cloud:
    client:
      hostname: localhost
  application:
    name: PortalWebAdmin  # Identify this application


  thymeleaf:
    cache: false # false : 서버 재시작 없이 새로고침.  개발서버 이상부터는 true로 설정.

    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    mode: XHTML
    prefix: /WEB-INF/views/
    suffix: .html
    # template-resolver-order:
    # view-names:

  http:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      location: ${java.io.tmpdir}

  servlet:
    multipart:
      enabled: ${spring.http.multipart.enabled}
      max-file-size: ${spring.http.multipart.max-file-size}
      max-request-size: ${spring.http.multipart.max-request-size}
      location: ${spring.http.multipart.location}


management:
  security:
    enabled: false

keycloak.:
  realm: eGovCP
  resource: cfAdminConsole
  auth-server-url: https://keycloak.mgmt.dev.egovp.kr/auth
  ssl-required: none
  public-client: true
  enabled: true


# HTTP Server
server:
  port: ${PORT:8090}   # HTTP (Tomcat) port
  session-timeout: 300
  tomcat:
  use-forward-headers: true
  error:
    whitelabel:
      enabled: false
  address:

paasta:
  portal:
    api:
      authorization:
        base64: Basic YWRtaW46b3BlbnBhYXN0YQ==
      zuulUrl:
        #cfapi: http://220.73.22.204:9042/portalapi # YOUR LOCAL TEST SETTING
        cfapi: http://localhost:2225/portalapi # YOUR LOCAL TEST SETTING
        commonapi: http://localhost:2225/commonapi # YOUR LOCAL TEST SETTING
        storageapi: http://localhost:2225/storageapi # YOUR LOCAL TEST SETTING
    storageapi:
      type: swift
logging:
  level:
    org.openpaas.paasta.portal.web.admin.exception.GlobalControllerExceptionHandler: DEBUG

cf:
  uaaDomain: https://uaa.mgmt.test.egovp.kr
  portalClient: adminclient
  clientSecret: clientsecret
  logoutRedirectUrl: https://localhost:8090/index

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2221/eureka/ #YOUR LOCAL TEST SETTING
      registry-fetch-interval-seconds: 5
  instance:
    hostname: ${spring.cloud.client.hostname}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address:
