server:
  port: 4545

spring:
  application:
    name: integration
# datasource:
#   driver-class-name: org.mariadb.jdbc.Driver
#   #    url: "jdbc:mariadb://localhost:7676/broker?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul"
#   url: "jdbc:mariadb://localhost:3306/service?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul"
#   #    username: admin
#   username: root
#   #    password: service@catalog
#   password: 8453
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
      show-sql: true
  rabbitmq:
    #    host: rabbitmq.dev.egovp.kr
    host: localhost
    port: 5672
    #    username: admin
    #    password: uocYoYvV2OSIGLiw8MJQ
    username: inhoon
    password: inhoon
    connection-timeout: 100000
    listener.direct.retry.enabled: true
    template.retry.enabled: true



config:
  vault:
    path: /secret/data/test/portal/svcbroker/
  rabbitmq:
    queue-name: sc.queue
    exchange-name: sc.topic
    routing-key: egovplatform.*.sc.*
    response:
      mp:
        topic: mp.topic
        routing: egovplatform.*.mp.*
      up:
        topic: up.topic
        routing: egovplatform.*.up.*
      cm:
        topic: cm.topic
        routing: egovplatform.*.cm.*

db1:
  datasource:
    #url: jdbc:mariadb://localhost:3306/service?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    #username: root
    #password: 8453
    #driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:7676/broker?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul"
    username: admin
    password: service@catalog
    driver-class-name: org.mariadb.jdbc.Driver


db2:
  datasource:
   url: jdbc:mariadb://localhost:3309/ECP_IAAS
   #username: root
   #password: 8453
   #driver-class-name: org.mariadb.jdbc.Driver
  #url: jdbc:mariadb://220.73.22.204:9330/ECP_IAAS?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
   username: catalog
   password: catalog
   driver-class-name: org.mariadb.jdbc.Driver
   maximum-pool-size: 16
   connectionTimeout : 10000
   max-lifetime: 240000

logging:
  level: debug
