#release setting 
releases_name: "cf-console-release"

#stemcell setting
stemcell_os: "ubuntu-xenial"
stemcell_version: latest
stemcell_alias: "default"

#paasta dependency
paasta_deployment_name: "paasta"
paasta_network_name: "default"
paasta_public_haproxy_network_name: "vip"
paasta_domain: "mgmt.dev.egovp.kr"
cc_db_id: "cloud_controller"
cc_db_password: "cc_admin"
uaa_db_id: "uaa"
uaa_db_password: "master77!!"

#network setting
internal_networks_name: "default"
external_networks_name: "vip"    #use-haproxy-public options....
haproxy_public_ip: "10.182.164.86"  #haproxy-public ip

#flavor setting
vm_type_tiny: "small"
vm_type_small: "small"
vm_type_medium: "portal_medium"

#portal database setting
mariadb_disk_type: "20GB"
mariadb_port: "3306"
mariadb_user_password: "cLOUDFOUNDRY@2020"

#portal storage setting
binary_storage_disk_type: "10GB"
binary_storage_username: "paasta-portal"
binary_storage_password: "paasta"
binary_storage_tenantname: "paasta-portal"
binary_storage_email: "paasta@paasta.com"

#cloudfoundry setting
cf_admin_password: "master77!!"
cf_uaa_admin_client_secret: "admin-secret"
rabbitmq_host_ip: "rabbitmq.dev.egovp.kr"
rabbitmq_port: "30002"
rabbitmq_username: "admin"
rabbitmq_password: "uocYoYvV2OSIGLiw8MJQ"

rabbitmq_queue_name: "cf.queue"
rabbitmq_exchange_name: "cf.topic"
rabbitmq_routing_key: "egovplatform.*.cf.*"
rabbitmq_response_mp_topic_name: "mp.topic"
rabbitmq_response_mp_routing_name: "egovplatform.*.mp.*"
rabbitmq_response_up_topic_name: "up.topic"
rabbitmq_response_up_routing_name: "egovplatform.*.up.*"

vault_host: "vault.mgmt.dev.egovp.kr"
vault_port: "80"
vault_token: "s.077H8ClcntRvzh5UPmQIWGTn"
vault_path: "/secret/data/dev/cf/"

#user portal, abacus, paasta-monitoring setting
paas_ta_web_user_url: "https://cf.console.dev.egovp.kr"
egov_platform_user_url: "https://www.dev.egovp.kr/eGovPlatform/user/app/user/login"
abacus_url: "http://abacus.111.111.111.111.xip.io"
monitoring_api_url: "http://192.168.22.105:8080"


#mail smtp setting
mail_smtp_host: "smtp.gmail.com"
mail_smtp_port: "465"
mail_smtp_username: "smtp_user_name"
mail_smtp_password: "smtp_password"
mail_smtp_useremail: "smtp_usermail@gmail.com"
mail_smtp_properties_auth: "true"
mail_smtp_properties_starttls_enable: "true"
mail_smtp_properties_starttls_required: "true"
mail_smtp_properties_subject: "PaaS-TA User Potal"


portal_webuser_monitoring: true
portal_webuser_quantity: false
portal_webuser_automaticapproval: false
portalclinet_secret: clientsecret

#spirng admin setting(not true)
infra_admin: false
vault_iaas: /secret/data/dev/portal/iaas/
vault_list: /secret/metadata/dev/cf
bosh_id: admin
bosh_secret: e6mlw21gvk9bkbnb64ep
bosh_url: https://192.168.22.35:25555
bosh_oauth_url: https://192.168.22.35:8443
bosh_cert: ""
ssh_url: ubuntu@10.182.164.18
bosh_env: micro-bosh
bosh_stemcell_path: /home/ubuntu/workspace/paasta-5.0/stemcell/paasta/bosh-stemcell-315.64-openstack-kvm-ubuntu-xenial-go_agent.tgz
portalclient_client: cfconsole
portalclient_auth_url: https://keycloak.mgmt.dev.egovp.kr/auth
portalclient_realm: eGovCP
portalclient_logout_url: https://cf.console.dev.egovp.kr/sso/logout
key_realm : eGovCP-Admin
key_client : cfAdminConsole
key_url : https://keycloak.mgmt.dev.egovp.kr/auth
bosh_path: "/home/ubuntu/workspace/user/PAAS-TA-PORTAL-API-RELEASE/deployments/bosh_profile.sh"
syslog_ip: 192.168.22.189
metric_url: 192.168.22.80:8049

